apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: notes-app-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - appName: notes-app
        path: applicationsets/notes-app
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/sagarendure-bit/ArgoCD-all.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
